# vim: ft=dockerfile
FROM debian:stable

RUN cd / && \
    echo 'APT::Install-Recommends "0";' > \
      /etc/apt/apt.conf.d/no_recommends && \
    echo 'APT::Get::AutomaticRemove "1";' >> \
      /etc/apt/apt.conf.d/no_recommends && \
    DEBIAN_FRONTEND=noninteractive \
      apt-get --yes update && \
    DEBIAN_FRONTEND=noninteractive \
      apt-get --yes upgrade && \
    DEBIAN_FRONTEND=noninteractive \
      apt-get --yes install \
        build-essential \
        dpkg-dev \
        libeccodes-data \
        libeccodes-dev \
        libeccodes-tools \
        python3-dev \
        python3-full \
        python3-pip \
        wget

COPY start mail2grib.py codec.py requirements.txt /GRIB-via-inReach/
# This one has to be provided:
COPY .mail-conf.json /GRIB-via-inReach/

# Install all dependencies using pip:
WORKDIR /GRIB-via-inReach
RUN python3 -m venv venv && \
    . venv/bin/activate && \
    pip install --use-pep517 eccodes && \
    pip install --use-pep517 -r requirements.txt

ENV ATTACHMENTS_PATH=/GRIB-via-inReach/attachments

LABEL maintainer="rixed@happyleptic.org"
ENTRYPOINT ["/GRIB-via-inReach/start"]
