# vim: ft=dockerfile
FROM debian:bookworm

RUN cd / && \
    echo 'APT::Install-Recommends "0";' > \
      /etc/apt/apt.conf.d/no_recommends && \
    echo 'APT::Get::AutomaticRemove "1";' >> \
      /etc/apt/apt.conf.d/no_recommends && \
    DEBIAN_FRONTEND=noninteractive \
      apt-get --yes update && \
    DEBIAN_FRONTEND=noninteractive \
      apt-get --yes upgrade && \
    DEBIAN_FRONTEND=noninteractive \
      apt-get --yes install \
        build-essential \
        dpkg-dev \
        libeccodes-data \
        libeccodes-dev \
        libeccodes-tools \
        python3-dev \
        python3-full \
        python3-cfgrib \
        python3-attr \
        python3-certifi \
        python3-cffi \
        python3-charset-normalizer \
        python3-click \
        python3-eccodes \
        python3-findlibs \
        python3-idna \
        python3-imap-tools \
        python3-numpy \
        python3-packaging \
        python3-pandas \
        python3-pycparser \
        python3-pyproj \
        python3-dateutil \
        python3-pytzdata \
        python3-tz \
        python3-pytz-deprecation-shim \
        python3-requests \
        python3-six \
        python3-urllib3 \
        python3-xarray \
        wget

COPY start mail2grib.py codec.py requirements.txt /GRIB-via-inReach/
# This one has to be provided:
COPY .mail-conf.json /GRIB-via-inReach/

# Install all dependencies using pip:
WORKDIR /GRIB-via-inReach
RUN python3 -m venv venv && \
    venv/bin/pip install pygrib

ENV ATTACHMENTS_PATH=/GRIB-via-inReach/attachments

LABEL maintainer="rixed@happyleptic.org"
ENTRYPOINT ["/GRIB-via-inReach/start"]
